# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8fadbed7aa57cf16f806333e3f01577f834b917e53a405bb6c7124196d6de09b54b643f88647a24adb849e8ea5dc266a174cbdfd522ac827c497115be85cf3db

test:
  secret_key_base: 1e1f91264f157cb7dd283479aaf5a4fb462ac33fa7f931b5e19cd011465b00b136976584e5fda755a4729f6c1b5fed596f57c6139f67c5e2a720bb64267edeb8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
